# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#kicknewbuild
# at the top of your YAML file 
# set some variables that you'll need when you deploy
variables:
  # the name of the service connection that you created above
  serviceConnectionToAzure: azurewebapp
  # the name of your web app here is the same one you used above
  # when you created the web app using the Azure CLI
  appName: webapptestdevops



trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(Build.Repository.LocalPath)
- script: echo $(Build.BinariesDirectory)
#  workingDirectory: $(Build.Repository.LocalPath)
#  displayName: List contents of a folder

- script: dir
  workingDirectory: $(Build.Repository.LocalPath)
  displayName: List contents of a folder


- script: dir
  workingDirectory: $(Build.BinariesDirectory)
  displayName: List contents of a folder



- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
 #   sonarQubeRunAnalysis: true
 #   sqMavenPluginVersionChoice: 'latest'
# add these as the last steps (below all the other `task` items under `steps`)
# to deploy to your app service

    
#- task: SonarCloudPrepare@1
 # inputs:
  #  SonarCloud: 'sonarcloud'
  #  organization: 'fireburn22-github'
  #  scannerMode: 'CLI'
  #  configMode: 'manual'
   # cliProjectKey: 'fireburn22_spring-framework-petclinic'
   # cliProjectName: 'spring-framework-petclinic'


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'fireburn22-github'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'fireburn22_spring-framework-petclini'
    cliProjectName: 'spring-framework-petclinic'
    cliSources: '.'
    extraProperties: 'sonar.projectBaseDir=/home/vsts/work/1/s/target'
   
    

- task: SonarCloudAnalyze@1

#- script: dir
 # workingDirectory: $(Build.BinariesDirectory)
 # displayName: List contents of a folder
  
- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)
    Contents: '*'
    TargetFolder: $(build.artifactstagingdirectory)

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)


#- task: AzureWebApp@1
#  displayName: Azure Web App Deploy
#  inputs:
#    azureSubscription: $(serviceConnectionToAzure)
#    appType: webAppLinux
#    appName: $(appName)
#    package: $(build.artifactstagingdirectory)/**/*.war